name: Deploy Radix Sort to Docker Hub

on:
  workflow_run:
    workflows: ["Test Radix Sort Implementation"]
    branches: [master]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build and Push Docker Image
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Build Docker image
        run: docker build -t radix-sort .
        
      - name: Tag Docker image
        run: |
          docker tag radix-sort ${{ secrets.DOCKER_HUB_USERNAME }}/radix-sort:latest
          docker tag radix-sort ${{ secrets.DOCKER_HUB_USERNAME }}/radix-sort:${{ github.sha }}
          
      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/radix-sort:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/radix-sort:${{ github.sha }}